title: Novi Sad New York 
description: Hanibal ante portas

url: http://novisadnewyork.com/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: O meni
   url: /about
 - title: Kontakt
   url: /contact

social:
   github: novisadnewyork
   facebook: zelena.jejka
   email: jelzelenovic@gmail.com

google_analytics: "UA-72819558-1"
